package cs5530;

import java.sql.ResultSet;
import java.sql.Statement;

import databaseOps.Insert;
import databaseOps.QueryResult;

import models.Customer;

public class CustomerOperations {
	
	public String registerUser(Statement stmt, Customer customer) throws Exception{
		String query = "";
		String resultstr="";
		QueryResult<Customer> result;
		ResultSet autoKeys;
				
		try{
			result = Insert.from(customer).execute(stmt);
			autoKeys = result.autoGeneratedKeys;
			query = result.sql;
        } catch(Exception e) {
			System.err.println("Unable to execute query: "+ query);
	                System.err.println(e.getMessage());
			throw(e);
		}
		System.out.println("Register:registerUser query="+query+"\n");
		resultstr = "Successful Register. Auto-Gen Keys: "+autoKeys;
		return resultstr;
	}
}
