package databaseOps;

import java.sql.SQLException;
import java.sql.Statement;

import models.IDbModel;

public class Update<T extends IDbModel> extends DatabaseOp<T>{

	private Update(T table)
			throws IllegalArgumentException, IllegalAccessException, InstantiationException {
		super(table);
	}

	public static <T extends IDbModel> Update<T> set(T table) throws IllegalArgumentException, IllegalAccessException, SQLException, InstantiationException{
		return new Update<T>(table);
	}

	@Override
	public QueryResult<T> execute(Statement stmt) throws SQLException {
		sql = "update "+tableName+" set ";
		
		for (String name : values.keySet())
			sql += name + "=" + values.get(name) + ",";
		sql = removeLastComma(sql);
				
		sql += whereStr;
		
		//save results
		QueryResult<T> result = new QueryResult<T>();
		result.sql = sql;
		stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
		result.setAutoGeneratedKeys(stmt.getGeneratedKeys());
		return result;
	}
}
